"""was_transferred flag

Revision ID: 18ca1adb2403
Revises: 275f950e5d3d
Create Date: 2026-07-22 21:44:21.322419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ca1adb2403'
down_revision: Union[str, Sequence[str], None] = '275f950e5d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so SQLite can add this NOT NULL column to a table that
    # already has rows; existing transactions simply weren't transferred.
    op.add_column(
        'transactions',
        sa.Column('was_transferred', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'was_transferred')
    # ### end Alembic commands ###
