"""notifications and duplicate flags

Revision ID: 275f950e5d3d
Revises: b17cb77d7715
Create Date: 2026-07-21 00:27:29.903917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275f950e5d3d'
down_revision: Union[str, Sequence[str], None] = 'b17cb77d7715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='notificationseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('related_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('related_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='notificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event_type'), 'notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_notifications_related_transaction_id'), 'notifications', ['related_transaction_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('duplicate_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('duplicate_of_transaction_id', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_fields', sa.Text(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'dismissed', name='duplicateflagstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_flags_detected_at'), 'duplicate_flags', ['detected_at'], unique=False)
    op.create_index(op.f('ix_duplicate_flags_duplicate_of_transaction_id'), 'duplicate_flags', ['duplicate_of_transaction_id'], unique=False)
    op.create_index(op.f('ix_duplicate_flags_notification_id'), 'duplicate_flags', ['notification_id'], unique=False)
    op.create_index(op.f('ix_duplicate_flags_status'), 'duplicate_flags', ['status'], unique=False)
    op.create_index(op.f('ix_duplicate_flags_transaction_id'), 'duplicate_flags', ['transaction_id'], unique=False)
    # server_default so SQLite can add this NOT NULL column to a table that
    # already has rows; existing transactions simply get "none".
    op.add_column(
        'transactions',
        sa.Column('duplicate_flag_status', sa.String(length=30), nullable=False, server_default='none'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'duplicate_flag_status')
    op.drop_index(op.f('ix_duplicate_flags_transaction_id'), table_name='duplicate_flags')
    op.drop_index(op.f('ix_duplicate_flags_status'), table_name='duplicate_flags')
    op.drop_index(op.f('ix_duplicate_flags_notification_id'), table_name='duplicate_flags')
    op.drop_index(op.f('ix_duplicate_flags_duplicate_of_transaction_id'), table_name='duplicate_flags')
    op.drop_index(op.f('ix_duplicate_flags_detected_at'), table_name='duplicate_flags')
    op.drop_table('duplicate_flags')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_transaction_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
