"""eod and business_date

Revision ID: b17cb77d7715
Revises: 7b3f53f27b9a
Create Date: 2026-07-21 00:14:28.840130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17cb77d7715'
down_revision: Union[str, Sequence[str], None] = '7b3f53f27b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_closures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('closed', 'reopened', name='eodstatus'), nullable=False),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reopened_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_closures_business_date'), 'eod_closures', ['business_date'], unique=True)
    # ### end Alembic commands ###

    # business_date added as nullable, backfilled from created_at (SQLite can't
    # add a NOT NULL column with no default to a table that already has rows),
    # then tightened to NOT NULL via batch mode.
    op.add_column('transactions', sa.Column('business_date', sa.Date(), nullable=True))
    op.execute("UPDATE transactions SET business_date = date(created_at) WHERE business_date IS NULL")
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('business_date', nullable=False)
        batch_op.create_index(op.f('ix_transactions_business_date'), ['business_date'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.drop_index(op.f('ix_transactions_business_date'))
        batch_op.drop_column('business_date')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eod_closures_business_date'), table_name='eod_closures')
    op.drop_table('eod_closures')
    # ### end Alembic commands ###
